eno=int(input("Please enter employee number:"))
ename=input("Please enter employee name:")
esal=int(input("Please enter employee salary:"))
eaddr=input("Please enter employee address:")
# married=bool((input("Is employee maried or not:[True(1) or False(0)]")))
# married=bool(int(input("Is employee maried or not:[True(1) or False(0)]")))
married=eval(input("Is employee maried or not:[True(1) or False(0)]"))

print("Please confirm details:")
print("Number:",eno)
print("Name:",ename)
print("salary:",esal)
print("address:",eaddr)
print("married status:",married)